var os = require("os")

console.log(os.EOL)
console.log(os.availableParallelism())
console.log(os.arch())
//console.log(os.constants)
//console.log(os.cpus())
console.log(os.devNull)
console.log(os.freemem())
console.log(os.hostname())
console.log(os.loadavg())
console.log(os.machine())
console.log(os.networkInterfaces())
console.log(os.platform())
console.log(os.release())
console.log(os.type())
console.log(os.uptime())
console.log(os.version())